title: Pinecone
description: >-
  Peer-to-Peer overlay router for the Matrix protocol!
baseurl: "/pinecone" # the subpath of your site, e.g. /blog
url: ""
twitter_username: matrixdotorg
github_username: matrix-org
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
aux_links:
  "GitHub":
    - "//github.com/matrix-org/pinecone"
aux_links_new_tab: true
sass:
  sass_dir: _sass
  style: compressed
exclude:
