# Based on https://github.com/docker/build-push-action

name: "Docker"

on:
  workflow_dispatch: # A build was manually requested
  workflow_call: # Another pipeline called us

env:
  GHCR_REPOSITORY: matrix-org/pinecone
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  build:
    name: Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get release tag
        if: github.event_name == 'release' # Only for GitHub releases
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Containers
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        if: github.ref_name == 'main'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_REPOSITORY }}:${{ github.ref_name }}
